# Config data exposed by config server
{
  "name": "master",
  "profiles": ["dev"],
  "label": null,
  "version": "81fcd86c0c99cb26d4060813252b3d306603789d",
  "state": null,
  "propertySources": [ https://www.google.com/
    {
      "name": "https://github.com/ericdahl/spring-cloud-config-example/server-config/application.yml",
      "source": {
        "info.foo": "bar",
        "info.someList[0]": 2,
        "info.someList[1]": 3,
        "info.someList[2]": 7
      }
    }
  ]
}
